= deduplicator
:icons: font

Find duplicate files. The duplicates are found by comparing SHA-512 hashsums.
Right now the app uses a postgresql database.

.Download
latest version: https://github.com/nils-gg/deduplicator/raw/master/out/artifacts/deduplicator_jar/deduplicator.jar[deduplicator.jar]

.Perquisites
In order to use the deduplicator you will need a working PostgreSQL installation,
with a database _filedb_ and a working database user.

Furthermore you need a JVM that can interpret java version 1.8 or newer.

== Usage
The first time you run the program, a wizard will help you to create a config file (config.properties).

.Start
[source, bash]
java -jar deduplicator.jar

== Future
* Make the app use a plaintext configuration file **(done)**
** specify default fileroot to search from **(done)**
** what kind of files should be compared (images, video, text..., all)
** DB user settings **(done)**
** should the app search for new files, or just continue to hash unhashed files from the db **(done)**
** maybe some kind of wizard to create the config file **(done)**
* Copy all unique files into a folder
** choose different naming schemes.
* Add the ability to compare files from different computers.
** copy unique files to a folder on a different computer (using SSH2)
